name: university
recipe: wordpress
config:
  webroot: wordpress
  php: '8.2'
services: 
  pma:
    type: phpmyadmin
    hosts:
      - database
    overrides:
      environment:
        PMA_HOST: database
        PMA_USER: wordpress
        PMA_PASSWORD: wordpress
